apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  tasks:
    - name: npminstall
      taskRef:
        name: npm
    - name: tests
      taskRef:
        name: Jasmine
      runAfter:
        - npminstall
    - name: build
      # build tasks
      taskRef:
        name: build
      runAfter:
        - tests
