apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  steps:
    - name: npminstall
      image: node:18
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: Jasmine
spec:
  steps:
    - name: tests
      image: node:18
      script: |
        npm test
